
services:
  db:
    image: postgres:latest
    container_name: uptime_db
    restart: always
#    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /tmp
      - /run
      - /var/run/postgresql

  adminer:
    image: adminer
    container_name: uptime_adminer
    restart: always
#    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"

  app:
    build: .
    container_name: uptime_app
    restart: always
#    read_only: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
    environment:
      DB_URL: postgresql://monitor:monitor@db:5432/monitor
#      URLS: "https://google.com,https://github.com"
      CHECK_INTERVAL: 60
      SLACK_WEBHOOK: ""
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
#      sh -c "uvicorn src.api:app --host 0.0.0.0 --port 8000 & python src/app.py"
    ports:
      - "8000:8000"
#      - "5000:5000"
    tmpfs:
      - /tmp

  worker:
    build: .
    container_name: uptime_worker
    restart: always
#    read_only: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql://monitor:monitor@db:5432/monitor
      URLS: "https://google.com,https://github.com"
      CHECK_INTERVAL: 60
      SLACK_WEBHOOK: ""
    command: python src/worker.py
#    ports:
#      - "8000:8000"
#      - "5000:5000"
    tmpfs:
      - /tmp

volumes:
  db_data:

