name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: uptime-monitor
  REGISTRY: ghcr.io
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - run: pip install -r requirements.txt
      - run: pip install flake8 black mypy

      - run: flake8 src
      - run: black --check src
      - run: mypy src

  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: auto
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: pip install -r requirements.txt
      - run: pip install pytest

      - run: pytest

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: unit-tests

    env:
      IMAGE_NAME: uptime-monitor

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t $IMAGE_NAME:ci .

      - name: Save image to tar
        run: docker save $IMAGE_NAME:ci -o image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  image-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose up -d --build

      - name: Wait for API
        run: |
          for i in {1..20}; do
            curl -f http://localhost:8000/status && break
            sleep 2
          done

      - run: docker compose down


  orca:
    name: Orca Security Scan
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - uses: actions/checkout@v4

      - name: Orca scan
        run: |
          echo "Orca scan"

  push-image:
    name: Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: [image-tests, orca]

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: uptime-monitor

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: docker load -i image.tar

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          docker tag $IMAGE_NAME:ci $IMAGE:latest
          docker tag $IMAGE_NAME:ci $IMAGE:${{ github.sha }}

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}


  deploy-dev:
    name: Deploy to Dev / Stage
    runs-on: ubuntu-latest
    needs: push-image

    steps:
      - run: echo "Deploy to DEV/STAGE environment"

  smoke-tests:
    name: Smoke / E2E Tests
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - run: echo "Run smoke tests against DEV/STAGE"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: smoke-tests
    environment:
      name: production

    steps:
      - run: echo "Deploying to production ðŸš€"

